services:
  # A Docker web service
  - type: web
    name: uptime-kuma
    env: docker
    region: Singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3001
